name: sanity_client_flutter
description: un-offcial sanity dart client.
version: 0.0.1
author: Rex Isaac Raphael
homepage: https://github.com/juicycleff/sanity_dart_client

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  rxdart: ^0.24.1

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
